// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/liukunc9/hertz_template/initialize"
)

func main() {
	initialize.DoInit()

	h := server.Default()
	register(h)
	h.Spin()
}
