// Code generated by hertz generator.

package sys

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	sys "github.com/liukunc9/hertz_template/biz/model/sys"
)

// SaveUser .
// @router /api/v1/sys/user [POST]
func SaveUser(ctx context.Context, c *app.RequestContext) {
	var err error
	var req sys.SaveUserReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(sys.SaveUserResp)

	c.JSON(consts.StatusOK, resp)
}

// GetUser .
// @router /api/v1/sys/user [GET]
func GetUser(ctx context.Context, c *app.RequestContext) {
	var err error
	var req sys.GetUserReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(sys.GetUserResp)

	c.JSON(consts.StatusOK, resp)
}

// UpdateUser .
// @router /api/v1/sys/user/:id [PUT]
func UpdateUser(ctx context.Context, c *app.RequestContext) {
	var err error
	var req sys.UpdateUserReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(sys.UpdateUserResp)

	c.JSON(consts.StatusOK, resp)
}
