// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSysUser = "sys_user"

// SysUser mapped from table <sys_user>
type SysUser struct {
	ID       int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键" json:"id"` // 主键
	UserID   string `gorm:"column:user_id;comment:用户id" json:"user_id"`                   // 用户id
	Name     string `gorm:"column:name;comment:姓名" json:"name"`                           // 姓名
	Age      int32  `gorm:"column:age;comment:年龄" json:"age"`                             // 年龄
	Address  string `gorm:"column:address;comment:地址" json:"address"`                     // 地址
	Password string `gorm:"column:password;not null;comment:密码" json:"password"`          // 密码
}

// TableName SysUser's table name
func (*SysUser) TableName() string {
	return TableNameSysUser
}
